server:
  port: 8080

# Oracle #
spring:
  application:
    name: rest
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: ${ORACLE_USR}
    password: ${ORACLE_PWD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update