
server:
  port: 8080

# Oracle #
spring:
  output:
    ansi:
      enabled: always
  application:
    name: rest
  datasource:
    url: ${DB_URL}
    driverClassName: org.postgresql.Driver
    username: ${DB_USR}
    password: ${DB_PWD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: debug